//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace South_Tech_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug
    {
        public System.Guid DrugID { get; set; }
        public System.Guid FacilityID { get; set; }
        public string Name { get; set; }
        public bool FDAApproved { get; set; }
        public string SideAffects { get; set; }
        public int Stock { get; set; }
        public string Description { get; set; }
    }
}
