//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace South_Tech_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacilityEvent
    {
        public System.Guid FacilityEventID { get; set; }
        public System.Guid PatientID { get; set; }
        public System.Guid FacilityID { get; set; }
        public int type { get; set; }
        public byte[] Timestamp { get; set; }
        public string Notes { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
